name: Frontend CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Frontend Docker image
      run: docker build -t cat-frontend:test .
    - name: Run tests
      run: |
        docker run -d -p 3000:3000 --name frontend-container cat-frontend:test
        sleep 10
        docker exec frontend-container npm run test