name: Frontend Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Frontend Docker image
      run: |
        docker build -t cat-ui:test -f Dockerfile .

    - name: Run Frontend container
      run: |
        docker run -d -p 3000:3000 --name frontend-container cat-ui:test
        # Wait for frontend to be ready
        sleep 10

    - name: Clean up
      if: always()
      run: |
        docker stop frontend-container || true
        docker rm frontend-container || true